"""Initial Migration

Revision ID: 1f79c8ddaf25
Revises: 7f911c0f6a7c
Create Date: 2022-03-05 22:00:27.484845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f79c8ddaf25'
down_revision = '7f911c0f6a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('add_description', sa.String(), nullable=True))
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'add_description')
    # ### end Alembic commands ###
